import React from 'react';
import { basementData } from '../basementData';

function Summary({ selections, totals, squareFootage, wallSquareFootage, skillLevel, onBack, onReset }) {
  
  const generateShoppingList = () => {
    const items = [];
    
    // Flooring
    if (selections.flooring) {
      items.push({
        category: 'Flooring',
        item: selections.flooring.name,
        quantity: `${squareFootage} sq ft`,
        estimatedCost: `$${Math.round(selections.flooring.costPerSqFt.min * squareFootage)} - $${Math.round(selections.flooring.costPerSqFt.max * squareFootage)}`
      });
    }
    
    // Wall Treatment
    if (selections.wallTreatment) {
      items.push({
        category: 'Wall Treatment',
        item: selections.wallTreatment.name,
        quantity: `${wallSquareFootage} sq ft`,
        estimatedCost: `$${Math.round(selections.wallTreatment.costPerSqFt.min * wallSquareFootage)} - $${Math.round(selections.wallTreatment.costPerSqFt.max * wallSquareFootage)}`
      });
    }
    
    // Multi-select categories
    ['lighting', 'spaceDivision', 'climateControl', 'extras'].forEach(category => {
      if (selections[category] && selections[category].length > 0) {
        selections[category].forEach(item => {
          items.push({
            category: basementData[category].title,
            item: item.name,
            quantity: '1 unit',
            estimatedCost: `$${item.costPerUnit.min} - $${item.costPerUnit.max}`
          });
        });
      }
    });
    
    return items;
  };

  const shoppingList = generateShoppingList();
  
  const printShoppingList = () => {
    const printWindow = window.open('', '', 'height=600,width=800');
    printWindow.document.write('<html><head><title>Basement Shopping List</title>');
    printWindow.document.write('<style>');
    printWindow.document.write('body { font-family: Arial, sans-serif; padding: 20px; }');
    printWindow.document.write('h1 { color: #2563eb; }');
    printWindow.document.write('table { width: 100%; border-collapse: collapse; margin-top: 20px; }');
    printWindow.document.write('th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }');
    printWindow.document.write('th { background-color: #f3f4f6; font-weight: bold; }');
    printWindow.document.write('.summary { background: #f9fafb; padding: 15px; margin: 20px 0; border-radius: 8px; }');
    printWindow.document.write('</style></head><body>');
    printWindow.document.write('<h1>Basement Improvement Shopping List</h1>');
    printWindow.document.write(`<p><strong>Basement Size:</strong> ${squareFootage} sq ft floor, ${wallSquareFootage} sq ft walls</p>`);
    printWindow.document.write(`<p><strong>Skill Level:</strong> ${skillLevel}</p>`);
    printWindow.document.write('<div class="summary">');
    printWindow.document.write(`<h3>Project Summary</h3>`);
    printWindow.document.write(`<p><strong>Total Estimated Cost:</strong> $${totals.costMin.toLocaleString()} - $${totals.costMax.toLocaleString()}</p>`);
    printWindow.document.write(`<p><strong>Total Estimated Time:</strong> ${totals.time} hours</p>`);
    printWindow.document.write(`<p><strong>Total Items:</strong> ${shoppingList.length}</p>`);
    printWindow.document.write('</div>');
    printWindow.document.write('<table>');
    printWindow.document.write('<tr><th>Category</th><th>Item</th><th>Quantity</th><th>Estimated Cost</th></tr>');
    shoppingList.forEach(item => {
      printWindow.document.write(`<tr><td>${item.category}</td><td>${item.item}</td><td>${item.quantity}</td><td>${item.estimatedCost}</td></tr>`);
    });
    printWindow.document.write('</table>');
    printWindow.document.write('<p style="margin-top: 30px; font-size: 12px; color: #666;">Generated by Basement Improvement Planner</p>');
    printWindow.document.write('</body></html>');
    printWindow.document.close();
    printWindow.print();
  };

  const copyShoppingList = () => {
    let text = 'BASEMENT IMPROVEMENT SHOPPING LIST\n\n';
    text += `Basement Size: ${squareFootage} sq ft floor, ${wallSquareFootage} sq ft walls\n`;
    text += `Skill Level: ${skillLevel}\n\n`;
    text += `ESTIMATED COST: $${totals.costMin.toLocaleString()} - $${totals.costMax.toLocaleString()}\n`;
    text += `ESTIMATED TIME: ${totals.time} hours\n\n`;
    text += 'SHOPPING LIST:\n';
    text += '─'.repeat(80) + '\n';
    
    shoppingList.forEach((item, index) => {
      text += `${index + 1}. ${item.category}: ${item.item}\n`;
      text += `   Quantity: ${item.quantity}\n`;
      text += `   Cost: ${item.estimatedCost}\n\n`;
    });
    
    navigator.clipboard.writeText(text).then(() => {
      alert('Shopping list copied to clipboard!');
    });
  };

  const hasSelections = shoppingList.length > 0;

  return (
    <div className="summary-container">
      <h1>Your Basement Plan</h1>
      
      <div className="totals-box">
        <div className="total-item">
          <span className="total-label">Estimated Cost Range</span>
          <span className="total-value cost">
            ${totals.costMin.toLocaleString()} - ${totals.costMax.toLocaleString()}
          </span>
        </div>
        
        <div className="total-item">
          <span className="total-label">Estimated DIY Time</span>
          <span className="total-value time">
            {totals.time} hours
          </span>
          <span className="total-sublabel">
            ({Math.round(totals.time / 8)} days at 8 hrs/day)
          </span>
        </div>
        
        <div className="total-item">
          <span className="total-label">Total Items Selected</span>
          <span className="total-value">
            {shoppingList.length}
          </span>
        </div>
      </div>

      {!hasSelections && (
        <div className="empty-state">
          <h3>No items selected yet</h3>
          <p>Go back and select some options to build your basement plan.</p>
        </div>
      )}

      {hasSelections && (
        <>
          <div className="selections-breakdown">
            <h2>Your Selections</h2>
            
            {Object.entries(selections).map(([category, selection]) => {
              if (!selection || (Array.isArray(selection) && selection.length === 0)) return null;
              
              const categoryData = basementData[category];
              const items = Array.isArray(selection) ? selection : [selection];
              
              return (
                <div key={category} className="category-breakdown">
                  <h3>{categoryData.title}</h3>
                  <div className="items-list">
                    {items.map((item, index) => (
                      <div key={index} className="breakdown-item">
                        <div className="item-name">
                          {item.name}
                          {item.waterResistant && <span className="water-badge">💧 Water Resistant</span>}
                        </div>
                        <div className="item-meta">
                          <span className={`difficulty-badge ${item.difficulty}`}>
                            {item.difficulty}
                          </span>
                          <span className="item-description">{item.description}</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>

          <div className="shopping-list-section">
            <h2>Shopping List</h2>
            
            <div className="action-buttons">
              <button className="btn btn-secondary" onClick={printShoppingList}>
                🖨️ Print List
              </button>
              <button className="btn btn-secondary" onClick={copyShoppingList}>
                📋 Copy to Clipboard
              </button>
            </div>

            <table className="shopping-table">
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Item</th>
                  <th>Quantity</th>
                  <th>Estimated Cost</th>
                </tr>
              </thead>
              <tbody>
                {shoppingList.map((item, index) => (
                  <tr key={index}>
                    <td>{item.category}</td>
                    <td>{item.item}</td>
                    <td>{item.quantity}</td>
                    <td>{item.estimatedCost}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="tips-section">
            <h3>💡 Tips for Your Project</h3>
            <ul>
              <li>Consider installing the dehumidifier first to control moisture during your project</li>
              <li>Start with flooring before adding furniture or dividers</li>
              <li>Test any adhesive products on a small area first</li>
              <li>Keep receipts and check return policies for unused materials</li>
              <li>Take "before" photos to appreciate your transformation!</li>
            </ul>
          </div>
        </>
      )}

      <div className="final-navigation">
        <button className="btn btn-secondary" onClick={onBack}>
          ← Back to Selections
        </button>
        <button className="btn btn-primary" onClick={onReset}>
          🔄 Start New Plan
        </button>
      </div>
    </div>
  );
}

export default Summary;
